import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Icon, IconType } from "./common/components/icon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex p-4 ">
                    <Sidebar />
                    {children}
                </main>
            </body>
        </html>
    );
}

function Sidebar() {
    return (
        <nav className="flex h-full min-w-[18rem] flex-col gap-6">
            <div>
                <h1 className="p-2 text-3xl">ul</h1>
            </div>
            <div className="justify-space-between flex flex-col gap-2">
                <SidebarItem href="/" text="Upcoming" icon="calendar" />
                <SidebarItem href="/lists" text="Lists" icon="list" />
                <SidebarItem href="/devices" text="Devices" icon="device" />
            </div>
        </nav>
    );
}

type SidebarItemProps = {
    href: string;
    text: string;
    icon?: IconType;
};
function SidebarItem({ href, text, icon }: SidebarItemProps) {
    return (
        <Link
            className="
        align-center
        flex 
        gap-3
        border-b-2
        border-solid
        border-gray-700
        p-2 
        hover:rounded-md  
        hover:bg-gray-700       
      "
            href={href}
        >
            {!!icon && <Icon icon={icon} />}
            {text}
        </Link>
    );
}
